<fieldset data-object="address">
	<legend>Address</legend>
	<label>Location Name</label>
	<input type="text" name="name" placeholder="Location Name">
	<label>Website</label>
	<input type="text" name="website" placeholder="website">
	<label>Address</label>
	<input type="text" name="line1" placeholder="Address">
	<label>Line 2</label>
	<input type="text" name="line2" placeholder="Line 2">
	<label>Line 3</label>
	<input type="text" name="line3" placeholder="Line 3">
	<label>City</label>
	<input type="text" name="city" placeholder="City">
	<label>State</label>
	<input type="text" name="state" placeholder="State">
	<label>Zip Code</label>
	<input type="text" name="zipcode" placeholder="Zip Code">
	<label>Country</label>
	<input type="text" name="country" placeholder="Country">
</fieldset>
<div class="contact">{% include "/_System/Apps/bcpie-profile/includes/contact.inc" %}</div>