<section id="core">
	<table class="files">
		<caption>Files</caption>
		<thead>
			<th>Type</th>
			<th>Name</th>
			<th>Version</th>
			<th>File</th>
			<th>Location</th>
			<th>Status</th>
			<th>Requires</th>
		</thead>
		<tbody>
			{{fileRows}}
			<tr class="emptyRow">
				<td colspan="7">No files.</td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="7">
					<ul class="button-group right radius">
						<li><button class="button tiny" data-bcpie-corefile="file:footScripts.js; location:foot; folder:Scripts;" type="submit">Create footScripts.js</button></li>
						<li><button class="button tiny warning" data-bcpie-corefile="file:headScripts.js; location:head; folder:Scripts;" type="submit">Create headScripts.js</button></li>
						<li><button class="button tiny success" data-bcpie-corefile="file:readyScripts.js; location:ready; folder:Scripts; minify:false" type="submit">Create readyScripts.js</button></li>
						<li><button class="button tiny alert" data-bcpie-corefile="file:ModuleStyleSheets.css; location:head; folder:StyleSheets;" type="submit">Create ModuleStyleSheets.css</button></li>
					</ul>
				</td>
			</tr>
		</tfoot>
	</table>
</section>