//@codekit-prepend "bower_components/foundation/js/vendor/jquery.js";
//@codekit-prepend "bower_components/foundation/js/vendor/jquery.cookie.js";
//@codekit-prepend "bower_components/foundation/js/vendor/fastclick.js";
//@codekit-prepend "bower_components/foundation/js/vendor/placeholder.js";
//@codekit-prepend "bower_components/responsive-tables/responsive-tables.js";
//@codekit-prepend "bower_components/selectize/dist/js/standalone/selectize.js";
//@codekit-prepend "jquery-ui.min.js";
//@codekit-prepend "min/iconic.min.js";
//@codekit-prepend "bcpie.js";
//@codekit-prepend "AutoSave/autosave.js";
//@codekit-prepend "Iris/iris.js";
//@codekit-prepend "Evan/webapp.js";
//@codekit-prepend "bower_components/foundation/js/foundation.js";
$(document).foundation();