<script>
	var globals = {{globals|json}};
		globals.pageName = '{module_pagename}';
		globals.pageAddress = '{{pageaddress}}';
		globals.primaryDomain = 'http://{module_sitehost}';
		globals.secureDomain = '{module_secureurl}';
</script>
<script src="/scripts/min/footScripts.min.js"></script>
<script src="/scripts/exampletrick.js"></script>
<script src="/scripts/readyScripts.js"></script>