<nav id="primary" role="navigation" data-bcpie-foundation="feature:topbar" class="top-bar">
	<ul class="title-area">
		<li class="name">
			<a href="/" class="logo"><img src="/images/general/logo.png" width="250" height="116"></a>
		</li>
		<li class="toggle-topbar menu-icon">
			<a href="#"><span>menu</span></a>
		</li>
	</ul>
	<section data-bcpie-activenav="true" class="top-bar-section">
		{module_menu, version="2", menuID="1480504", moduleTemplateGroup="Top Bar"}
	</section>
</nav>