{% include '{{appRoot}}logic/globals.inc' %}
<meta charset="utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="{{root}}styles/framework.css?6" />
<link rel="stylesheet" href="{{appRoot}}styles/app.css?9" />
<script src="//use.typekit.net/qeu2tdc.js"></script>
<script>try{Typekit.load();}catch(e){}</script>
<script src="{{root}}scripts/min/headScripts.min.js"></script>