<meta charset="UTF-8" />
<meta name="robots" content="noindex" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="{{root}}styles/framework.css" />
<link rel="stylesheet" href="{{root}}styles/app.css" />
<script src="//use.typekit.net/qeu2tdc.js"></script>
<script>try{Typekit.load();}catch(e){}</script>
<script src="{{root}}scripts/min/headScripts.min.js"></script>