{% include '/_System/Includes/library/pageaddress.inc' %}
{% include '/_System/Includes/library/profile.inc' %}
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta property="og:site_name" content="BC Pie"/>
<link rel="stylesheet" href="/stylesheets/modulestylesheets.css" />
<link rel="stylesheet" href="/stylesheets/theme.css" />
<link rel="stylesheet" href="/stylesheets/app.css" />
<link rel="shortcut icon" href="/images/general/favicon.png" />
<script src="/scripts/min/headScripts.min.js"></script>